# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('address_street', models.CharField(max_length=500)),
                ('address_city', models.CharField(max_length=500)),
                ('address_zipcode', models.CharField(max_length=500)),
            ],
        ),
    ]
