# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, null=True)),
                ('website', models.CharField(max_length=2000, null=True)),
                ('address_street', models.CharField(max_length=500, null=True)),
                ('address_city', models.CharField(max_length=500, null=True)),
                ('address_county', models.CharField(max_length=500, null=True)),
                ('address_state', models.CharField(max_length=50, null=True)),
                ('address_zip', models.CharField(max_length=500, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
        ),
    ]
