# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_auto_20170711_0509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='address_zipcode',
            new_name='address_zip',
        ),
    ]
