# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_auto_20170726_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='session_key',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_zip',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
