# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_auto_20170719_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='address_county',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
