# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_auto_20170806_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_key',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
